"""Manifest type strings and version constants for xeSim v0 artifacts."""

CROP_MANIFEST_TYPE = "xesim.crop_manifest.v0"
SPLIT_MANIFEST_TYPE = "xesim.splits.v0"
SYNTHETIC_MANIFEST_TYPE = "xesim.synthetic_manifest.v0"
STAIN_MODEL_TYPE = "xesim.parametric_stain_v0"
FIT_REPORT_TYPE = "xesim.fit_report.v0"
QC_REPORT_TYPE = "xesim.qc_report.v0"
TRAINING_REPORT_TYPE = "xesim.tiny_renderer_training.v0"
BACKGROUND_PROFILE_TYPE = "xesim.background_profile.v0"
ANCHOR_PROFILE_TYPE = "xesim.anchor_profile.v0"
SCENE_FIT_TYPE = "xesim.scene_fit.v0"
SCENE_PROBE_SUMMARY_TYPE = "xesim.scene_probe_summary.v0"
SCENE_REVIEW_TYPE = "xesim.scene_review.v0"
CELL_APPEARANCE_BENCHMARK_TYPE = "xesim.cell_appearance_benchmark.v0"
CELL_FLOW_CORPUS_TYPE = "xesim.cell_flow_corpus.v0"
CELL_FLOW_TRAINING_TYPE = "xesim.cell_flow_training.v0"
CELL_FLOW_SWEEP_TYPE = "xesim.cell_flow_sweep.v0"
MECHANISTIC_REFINER_CORPUS_TYPE = "xesim.mechanistic_refiner_corpus.v0"
MECHANISTIC_REFINER_TRAINING_TYPE = "xesim.mechanistic_refiner_training.v0"
MECHANISTIC_REFINER_SAMPLES_TYPE = "xesim.mechanistic_refiner_samples.v0"
MECHANISTIC_REFINER_EVAL_TYPE = "xesim.mechanistic_refiner_eval.v0"

MANIFEST_SCHEMA_VERSION = "0.1.0"
